kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-data
spec:
  storageClassName: standard
  # storageClassName: local-storage
  # storageClassName: ceph-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
